List<String> compliments = [
  "You’re that “Nothing” when people ask me what I’m thinking about.",
  "You look great today.",
  "You’re a smart cookie.",
  "I bet you make babies smile.",
  "You have impeccable manners.",
  "I like your style.",
  "You have the best laugh.",
  "I appreciate you.",
  "You are the most perfect you there is.",
  "Our system of inside jokes is so advanced that only you and I get it. And I like that.",
  "You’re strong.",
  "Your perspective is refreshing.",
  "You’re an awesome friend.",
  "You light up the room.",
  "You deserve a hug right now.",
  "You should be proud of yourself.",
  "You’re more helpful than you realize.",
  "You have a great sense of humor.",
  "You’ve got all the right moves!",
  "Is that your picture next to “charming” in the dictionary?",
  "Your kindness is a balm to all who encounter it.",
  "You’re all that and a super-size bag of chips.",
  "On a scale from 1 to 10, you’re an 11.",
  "You are brave.",
  "You’re even more beautiful on the inside than you are on the outside.",
  "You have the courage of your convictions.",
  "Aside from food. You’re my favorite.",
  "If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.",
  "You are making a difference.",
  "You’re like sunshine on a rainy day.",
  "You bring out the best in other people.",
  "Your ability to recall random factoids at just the right time is impressive.",
  "You’re a great listener.",
  "How is it that you always look great, even in sweatpants?",
  "Everything would be better if more people were like you!",
  "I bet you sweat glitter.",
  "You were cool way before hipsters were cool.",
  "That color is perfect on you.",
  "Hanging out with you is always a blast.",
  "You always know — and say — exactly what I need to hear when I need to hear it.",
  "You smell really good.",
  "You may dance like no one’s watching, but everyone’s watching because you’re an amazing dancer!",
  "Being around you makes everything better!",
  "When you say, “I meant to do that,” I totally believe you.",
  "When you’re not afraid to be yourself is when you’re most incredible.",
  "Colors seem brighter when you’re around.",
  "You’re more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
  "That thing you don’t like about yourself is what makes you so interesting.",
  "You’re wonderful.",
  "Everyday is just BLAH when I don’t see you For reals! (awesome – you are halfway through the list. You’re awesome!)",
  "Jokes are funnier when you tell them.",
  "You’re better than a triple-scoop ice cream cone. With sprinkles.",
  "Your bellybutton is kind of adorable.",
  "Your hair looks stunning.",
  "You’re one of a kind!",
  "You’re inspiring.",
  "If you were a box of crayons, you’d be the giant name-brand one with the built-in sharpener.",
  "You should be thanked more often. So thank you!!",
  "Our community is better because you’re in it.",
  "Someone is getting through something hard right now because you’ve got their back.",
  "You have the best ideas.",
  "You always know how to find that silver lining.",
  "Everyone gets knocked down sometimes, but you always get back up and keep going.",
  "You’re a candle in the darkness.",
  "You’re a great example to others.",
  "Being around you is like being on a happy little vacation.",
  "You always know just what to say.",
  "You’re always learning new things and trying to better yourself, which is awesome.",
  "If someone based an Internet meme on you, it would have impeccable grammar.",
  "You could survive a Zombie apocalypse.",
  "You’re more fun than bubble",
];

List<String> compliments2 = [
  'Simply \n stunning',
  'Amazing \n person',
  'Superb \n work',
  'Beautiful \n smile',
  'Fantastic \n job',
  'Terrific \n friend',
  'Incredible \n talent',
  'Lovely \n voice',
  'Exceptional \n skills',
  'Gorgeous \n hair',
  'Wonderful \n heart',
  'Brilliant \n mind',
  'Fabulous \n dancer',
  'Impressive \n effort',
  'Outstanding \n performance',
  'Awesome \n personality',
  'Great \n taste',
  'Marvelous \n creativity',
  'Terrific \n energy',
  'Stunning \n beauty',
  'Exceptional \n charm',
  'Incredible \n grace',
  'Perfect \n match',
  'Sweet \n soul',
  'Precious \n gem'
];
